DELIMITER //

CREATE PROCEDURE CheckTable(IN tableName VARCHAR(255))
BEGIN
    SET @s = CONCAT('CHECK TABLE ', tableName);
    PREPARE stmt FROM @s;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;
END //

DELIMITER ;