DELIMITER //

CREATE PROCEDURE OptimizeTable(IN tableName VARCHAR(255))
BEGIN
    SET @s = CONCAT('OPTIMIZE TABLE ', tableName);
    PREPARE stmt FROM @s;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;
END //

DELIMITER ;