DELIMITER //

CREATE PROCEDURE FlushTable(IN tableName VARCHAR(255))
BEGIN
    SET @s = CONCAT('FLUSH TABLES ', tableName);
    PREPARE stmt FROM @s;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;
END //

DELIMITER ;